version: '3'

services: 
    ploggy:
        build: ./
        env_file: 
            - ".env"
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./:/code
        ports:
            - 8000:8000
        expose:
            - "8000"
        networks:
            - postgres-net
        
    postgres:
        image: postgres:latest
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        networks: 
            - postgres-net
        volumes:
            - postgres-data:/mnt/usbdrive/ploggypostgres/



volumes:
    postgres-data:

networks:
    postgres-net: