# Generated by Django 3.1.3 on 2020-11-15 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoundData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decibels', models.FloatField()),
                ('entry_dt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity', models.FloatField()),
                ('temperature', models.FloatField()),
                ('entry_dt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='temperaturedata',
            index=models.Index(fields=['entry_dt'], name='data_temper_entry_d_6340f3_idx'),
        ),
        migrations.AddIndex(
            model_name='sounddata',
            index=models.Index(fields=['entry_dt'], name='data_soundd_entry_d_efef10_idx'),
        ),
    ]
